### ISSUE TITLE
Instantly crashes upon launch

### ISSUE THREAD

**Issue by Azure-Skyed** [CorkHQ/Cork#14]
https://github.com/CorkHQ/Cork/assets/143346971/a9e18bf7-6fa6-4f22-9097-13673a3eaa26

**Comment by Bugadinho** [comment]
That appears to be an issue related to Wine, could you share the log file located in `~/.cache/cork/logs/`?

**Comment by Azure-Skyed** [comment]
> That appears to be an issue related to Wine, could you share the log file located in `~/.cache/cork/logs/`?

Sorry, I actually figured out the problem. I was using the website and I didn't know i had to run the player to actually use it.

Works totally fine now and I can finally play roblox with my friends.

**Comment by Bugadinho** [comment]
That's great!
