### ISSUE TITLE
Shiftlock and First Person not working correctly

### ISSUE THREAD

**Issue by NikoN0777** [CorkHQ/Cork#15]
[video showing the error](https://raw.githubusercontent.com/NikoN0777/rahrah/main/2023-08-28%2007-57-20.mp4)
i encounter this on every game i join, unless they add a code that specifically makes the mouse lock in place
may just be a roblox error but im still putting this on here because it may be related to cork instead.

**Comment by Bugadinho** [comment]
This is most likely because you are running under Wayland, for now only X11 properly handles the cursor on Roblox.

**Comment by NikoN0777** [comment]
> This is most likely because you are running under Wayland, for now only X11 properly handles the cursor on Roblox.

yeah, using x11 fixed the issue.
