### ISSUE TITLE
Updating client

### ISSUE THREAD

**Issue by Noxylia** [CorkHQ/Cork#17]
I've been using this for Roblox for a week or two now, but it's been saying that it needs an update recently and I'm not sure how to do this.

**Comment by Bugadinho** [comment]
Could you take a screenshot of the message?

**Comment by Noxylia** [comment]
Nevermind, I just opened it now and I guess it figured it out. For the last
couple of days it had been crashing and saying that Roblox needed an update
to run. I suppose it's automatically updated whatever it is now. Thanks
anyways. I'll let you know how it goes.

**Comment by Bugadinho** [comment]
Alright then, keep in mind however that if you are using the `zintegration` channel, you can safely remote it now, as Wine support already reached the live channels.
