### ISSUE TITLE
using discrete gpu instead of integrated?

### ISSUE THREAD

**Issue by mitsuaka** [CorkHQ/Cork#22]
when launching the game, it uses integrated gpu instead of discrete one. is there any way to use discrete gpu for Roblox? if it includes modifying wine, please, tell the proper way to do it.

**Comment by Sabuntu** [comment]
Try manjaro

**Comment by Bugadinho** [comment]
By default, it uses the default GPU, which in this case is the integrated one. You can switch to using the dedicated one by either using DXVK or Proton, which automatically uses the dedicated GPU, or by adding PRIME's environment variables to the settings.json file.
