### ISSUE TITLE
Issue when installing Cork

### ISSUE THREAD

**Issue by RedrcknRbn** [CorkHQ/Cork#23]
When using `flatpak install --user Corky.flatpak`, I got the error `error: The application io.github.bugadinho.Corky/x86_64/master requires the runtime org.kde.Platform/x86_64/6.5 which was not found`.
Using `flatpak repair --user` then `sudo flatpak repair` didnt work.

**Comment by Bugadinho** [comment]
Try installing the runtime first by doing this:
```bash
flatpak install --user org.kde.Platform/x86_64/6.5
```

**Comment by RedrcknRbn** [comment]
`No remote refs found for ‘org.kde.Platform/x86_64/6.5’`

**Comment by Bugadinho** [comment]
Do you have flathub configured on your system?

**Comment by RedrcknRbn** [comment]
I use it for a whole bunch of my installs, so I have no clue why it's doing this.
```
[redd@archlinux ~]$ flatpak install --user flathub org.kde.Platform/x86_64/6.5
Looking for matches…
error: No remote refs found for ‘flathub’
```

**Comment by Bugadinho** [comment]
Perhaps it's because it's because of the `--user` argument, try installing at least just the runtime on the actual system like so, the user install of the app should pick it up:
```
flatpak install flathub org.kde.Platform/x86_64/6.5
```

**Comment by RedrcknRbn** [comment]
One restart later and it seems to have been fixed,
(leaving the issue open because can you tell me how to open and use cork now :P)

**Comment by WaviestBalloon** [comment]
No

**Comment by RedrcknRbn** [comment]
ok fair thanks
