### ISSUE TITLE
how do i uninstall

### ISSUE THREAD

**Issue by odiplol** [CorkHQ/Cork#25]
tried sudo apt remove, software center, etc. cant find the damn pkg!!!
debian12

**Comment by Bugadinho** [comment]
What install method did you use?

**Comment by odiplol** [comment]
pretty sure it was a debian package. sorry for late reply

**Comment by Bugadinho** [comment]
If it's the experimental one, the package should just be named `cork` and apt remove should be enough.

**Comment by odiplol** [comment]
nope. application not found

**Comment by Bugadinho** [comment]
Then it was probably installed with pip. To remove the package with pip just do the following:
```bash
pip uninstall --user cork-launcher
```

**Comment by odiplol** [comment]
no luck.

**Comment by odiplol** [comment]
turns out i installed via flatpak,  found this out by checking the shortcut, openinng the corky.platfak file opened gnome-software, and it was displayed as null, and i could remove it from their. nice.

**Comment by Bugadinho** [comment]
That's great!
