### ISSUE TITLE
What renderer does this use?

### ISSUE THREAD

**Issue by PikaDevs** [CorkHQ/Cork#26]
Heya! First of all, really nice job, this is the only way I can run studio - grapejuice nor vinegar work for me
However, it's a bit unstable (flickering when resizing windows, when I tried to open a big map, it all crashed and never could open again, had to delete all associated data with it and reinstall)

I'm wondering if this instability could be improved by changing the renderer, perhaps if it's using opengl we could use DX11 with DXVK (i saw that dxvk was marked as an enhancement earlier, so that'd be quite far off)?

Also is there a config file to modify? I'm using the flatpak so the location of it would be much appreciated, thanks!

**Comment by PikaDevs** [comment]
Oh, I think it's crashing whenever I try and open a cloud project which is interesting

**Comment by Bugadinho** [comment]
By default, Cork uses whatever Wine provides, in most cases it's WineD3D, but since in the Flatpak version we are using Proton GE, it's using DXVK. Also the settings file for the Flatpak version is in ```~/.var/app/io.github.CorkHQ.Corky/config```

**Comment by PikaDevs** [comment]
I see, thank you
