### ISSUE TITLE
Add support for rbxfpsunlocker

### ISSUE THREAD

**Issue by Kaydax** [CorkHQ/Cork#3]
Not sure if there needs to be something else added on in order to allow this to work or whatever, but it would be nice to have rbxfpsunlocker support built in

**Comment by Bugadinho** [comment]
While i do not plan on adding support for rbxfpsunlocker for the time being, you can unlock the frame cap by putting something like `"DFIntTaskSchedulerTargetFps": 1000` on the `fflags` section of the configuration file.

**Comment by bessonowjaroslaw** [comment]
how can i find fflags?

**Comment by Bugadinho** [comment]
> how can i find fflags?
> 

It's part of the `roblox` section on the settings.json file.

**Comment by computer-conservative** [comment]
Where can i even find the config file

**Comment by Bugadinho** [comment]
RCO is already supported, it's just a matter of taking the `https://raw.githubusercontent.com/L8X/Roblox-Client-Optimizer/main/ClientAppSettings.json` URL from RCO and putting it into the `remotefflags` option.
