### ISSUE TITLE
Cork 2 doesnt find libcpr.so.1 after installing

### ISSUE THREAD

**Issue by Flowcheer** [CorkHQ/Cork#30]
After installing Cork 2, when you try running any cork command, you get a missing library error
![imagen](https://github.com/CorkHQ/Cork/assets/79985497/a094cf5d-8f23-4374-8117-14d1b4613acc)

**Comment by Bugadinho** [comment]
The instructions on the readme might be a bit outdated, try using the following to build it:
```bash
git clone https://github.com/CorkHQ/Cork.git
cd Cork
mkdir build
cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCPR_USE_SYSTEM_CURL=ON
cmake --build build/ --target all
cd build
cmake --install . --prefix ~/.local
```
Let me know if it works!

**Comment by Flowcheer** [comment]
This worked first try, thanks!
