### ISSUE TITLE
Memory Dump Report

### ISSUE THREAD

**Issue by AngryBirdsFanboy06** [CorkHQ/Cork#33]
gives me an unavoidable error
![image](https://github.com/CorkHQ/Cork/assets/127870956/57d9e6aa-a4ba-4954-910e-6ba20c3a9391)
![image](https://github.com/CorkHQ/Cork/assets/127870956/83accbf6-aa46-450c-95a1-a189bf5d0200)

(link for the files)
https://drive.google.com/drive/folders/1OsJ0czW9DROyHl0cRSQrjKLE9WXheJRj?usp=sharing

**Comment by WaviestBalloon** [comment]
You might want to delete the dumps in your Google Drive.
**Memory dumps can contain sensitive information**, send a PM to Bitdancer on the DevForums: https://devforum.roblox.com/u/bitdancer

**Comment by AngryBirdsFanboy06** [comment]
Ok

**Comment by WaviestBalloon** [comment]
Remove the link from your original message

**Comment by AngryBirdsFanboy06** [comment]
The link itself is just an 404 error page now, no need of trying to remove it
