### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by Henry-Hiles** [CorkHQ/Cork#36]
Some readme improvements would be nice, such as screenshots, etc. Thanks!

**Comment by Bugadinho** [comment]
Sounds interesting, although i have no clue what i could add, suggestions of what to add would be nice.

**Comment by Henry-Hiles** [comment]
Maybe some screenshots, rn i have no idea if this is a gui like grapejucie or cli like vinegar, etc

**Comment by Bugadinho** [comment]
This is a CLI-only app, however a GUI version is planned in the future.

**Comment by Henry-Hiles** [comment]
I see, thanks!
