### ISSUE TITLE
After a while of playing, Roblox Player just freezes or crashes

### ISSUE THREAD

**Issue by RedrcknRbn** [CorkHQ/Cork#37]
Randomly after playing for a couple of minutes, a few things can happen. Sometimes Roblox completely freezes and I can't navigate using the mouse until I completely end the process, while other times it just crashes. 
Video of it freezing:
https://github.com/CorkHQ/Cork/assets/63996530/60f715a3-a925-42d1-82f6-40382268bc34
Video of it crashing:
https://github.com/CorkHQ/Cork/assets/63996530/66e8f37a-bfb6-4e27-8a3e-c1f578a0242a

**Comment by RedrcknRbn** [comment]
thank you github for not embedding my videos

**Comment by Bugadinho** [comment]
I've had this problem with an early version of Roblox that was shipped in the live channel, does this still persist currently?

**Comment by RedrcknRbn** [comment]
Still persists

**Comment by Noxylia** [comment]
I'm getting the same issue, the game will boot up and work fine for about 5-10 minutes, then it will suddenly crash. I don't receive any type of error message or anything. I can get a video of mine doing the same thing if it's needed.

**Comment by Bugadinho** [comment]
It appears this problem is happening due to a Roblox update, for now changing the version channel to "zavatarteam2" solves the issue.

**Comment by tygoee** [comment]
@Bugadinho Thanks that seems to work, can you make that the default version channel?

**Comment by RedrcknRbn** [comment]
> It appears this problem is happening due to a Roblox update, for now changing the version channel to "zavatarteam2" solves the issue. (found this in the Vinegar Discord)

Seems to be fixed after switching

**Comment by Noxylia** [comment]
I changed the channel and it now opens again, however I experience extreme lag which leads to the game crashing anyways after 10 minutes.
