### ISSUE TITLE
Where is the deb file mentioned on the README.md file?

### ISSUE THREAD

**Issue by MarkInCrack** [CorkHQ/Cork#55]
I am troubleshooting with the cmake command, and then i saw the deb file being mentioned,

By the way, does Cork still works?

-Thanks, for reading my issue

-Mark

**Comment by Bugadinho** [comment]
The deb package is located in the artifacts part of any given action, here is a direct link to one, the artifact on the bottom is what you want:
https://github.com/CorkHQ/Cork/actions/runs/9038325939

Cork does still work, however the Player does not, it's anti-cheat currently prevents it from running at all, however Studio should still work.
